### ISSUE TITLE
Missing rtlsdr_get_usb_strings()

### ISSUE THREAD

**Issue by gvanem** [old-dab/rtlsdr#4]
Since the very good commit to use only WinUSB for Win32-targets, the function
`rtlsdr_get_usb_strings()` got lost.  It's now outside the `_WIN32` section of `librtlsdr.c`.

This function is needed in Welle-IO etc.

I've tried to add it like:
```c
int rtlsdr_get_usb_strings (rtlsdr_dev_t *dev, char *manufact, char *product, char *serial)
{
  if (!dev || !dev->devh)
     return -1;
  // what to put here? 
  return rtlsdr_get_device_usb_strings (index, manufact, product, serial);
}
```

So how to get an `index` from a `dev`? There is no `dev->index` to get it from.

And BTW, this WinUSB rewrite is rock-solid compared to the previous libusb version. Good job!!

**Comment by old-dab** [comment]
You are right, rtlsdr_get_usb_string() is not available in my WinUSB version of librtlsdr.
rtlsdr_get_device_usb_strings() reads the windows registry.
"Index" is the number of the RTL2832 device, starting with 0. If you only have one device, index is 0.

In Welle-IO, try to use "rtl-tcp" instead of "rtl-sdr". That works fine.

**Comment by gvanem** [comment]
I've radically patched you library and added a `dev->index`. Works fine with Welle-IO now.
Hence closing.
